### ISSUE TITLE
Faculty Login

### ISSUE THREAD

**Issue by ShwetimaSakshi** [PhD-Annual-Review-System/PhD-Annual-Review-System#5]
As a student user with an account on the Ph.D. Annual Review System
So that I can create/update my profile
I want to use my username and password to login to my account from the 
login page

**Comment by jagtapshashank** [comment]
1. Create API specs for this page.
2. Connect it backend database.
3. Create database schema for login.

**Comment by harshsurolia2609-tamu** [comment]
Successfully implemented the login page for the faculty. Along with html and css
