### ISSUE TITLE
Spike: Authentication system

### ISSUE THREAD

**Issue by psurbhi** [PhD-Annual-Review-System/PhD-Annual-Review-System#9]
As as student or faculty member
So that I can access the PhD review system
I want to be able to login using authentication system

https://github.com/PhD-Annual-Review-System/PhD-Annual-Review-System/issues/1
This task is part of the Login main system story

**Comment by willdharper** [comment]
Uploaded pdf with our findings into the misc documentation folder and made a pull request to main.
